---
- name: Install Kubernetes Add-ons
  hosts: control_plane
  become: true
  tasks:
    - name: Download the official metrics-server manifest
      ansible.builtin.get_url:
        url: https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml
        dest: /tmp/metrics-server-components.yaml
        mode: '0644'

    - name: Add --kubelet-insecure-tls flag to the metrics-server deployment
      ansible.builtin.replace:
        path: /tmp/metrics-server-components.yaml
        regexp: '        - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname'
        replace: '        - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname\n        - --kubelet-insecure-tls'

    - name: Apply the patched metrics-server manifest
      become: true
      ansible.builtin.shell: |
        KUBECONFIG=/etc/kubernetes/admin.conf kubectl apply -f /tmp/metrics-server-components.yaml
      register: metrics_server_install_status
      changed_when: metrics_server_install_status.rc == 0

    - name: Check the status of the metrics-server pods
      become: false
      ansible.builtin.command: kubectl get pods -n kube-system -l k8s-app=metrics-server
      register: pod_status
      until: '"metrics-server" in pod_status.stdout'
      retries: 20
      delay: 10
      changed_when: false
      failed_when: "'Running' not in pod_status.stdout"

    - name: Download the Helm installation script
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
        dest: /tmp/get_helm.sh
        mode: '0700'
    
    - name: Execute the Helm installation script
      ansible.builtin.command: /tmp/get_helm.sh
      args:
        creates: /usr/local/bin/helm # This makes the task idempotent
      register: helm_install_status
      changed_when: helm_install_status.rc == 0

    - name: Clean up the downloaded script
      ansible.builtin.file:
        path: /tmp/get_helm.sh
        state: absent

    - name: Add 'k' alias for 'kubectl' to .bashrc
      become: false
      ansible.builtin.lineinfile:
        path: ~/.bashrc
        line: "alias k=kubectl"
        state: present

    - name: Add kubectl shell autocompletion to .bashrc
      become: false
      ansible.builtin.lineinfile:
        path: ~/.bashrc
        line: "source <(kubectl completion bash)"
        state: present

    - name: Add autocompletion rule for 'k' alias
      become: false
      ansible.builtin.lineinfile:
        path: "~/.bashrc"
        line: 'complete -F __start_kubectl k'
        state: present

    - name: Ensure .bashrc is sourced for the current shell
      become: false
      ansible.builtin.shell: "source ~/.bashrc"
      args:
        executable: /bin/bash
      changed_when: false